const content = [
  {
    id: 0,
    figure: 1,
    text: "el delirio de querer vivir muchos ritmos en una sola vida...",
    author: "Javier Bassas y Raquel Friera",
    title: "Instituto del Tiempo Suspendido",
  },
  {
    id: 1,
    figure: 1,
    text: "viene de tan lejos en el pasado e incumbe tanto al futuro que su fundación se encuentra, suspendida, dentro y fuera del tiempo...",
    author: "Javier Bassas y Raquel Friera",
    title: "Instituto del Tiempo Suspendido",
    image: "INSTITUTO1.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores",
  },
  {
    id: 2,
    figure: 1,
    text: "hacia la reapropiación del tiempo expropiado, robado, perdido por todas las prácticas que reducen la cronodiversidad constitutiva de los seres...",
    author: "Javier Bassas y Raquel Friera",
    title: "Instituto del Tiempo Suspendido",
  },
  {
    id: 3,
    figure: 1,
    text: "un agujero negro dentro de internet porque atrae y altera el tiempo de quien la visita...",
    author: "Javier Bassas y Raquel Friera",
    title: "Instituto del Tiempo Suspendido",
    image: "INSTITUTO4.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores",
  },
  {
    id: 4,
    figure: 1,
    text: "somos, cada cual, tiempos...",
    author: "Javier Bassas y Raquel Friera",
    title: "Instituto del Tiempo Suspendido",
    image: "INSTITUTO3.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores",
  },
  {
    id: 5,
    figure: 2,
    text: "la crononormatividad es un modo de implantación, una técnica por la que las fuerzas institucionales llegan a parecer hechos somáticos...",
    author: "Elisabeth Freeman",
    title: "Time Binds: Queer Temporalities, Queer Histories",
    image: "BIBLIOGRAFIA.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores",
  },
  {
    id: 6,
    figure: 2,
    text: "los horarios, los calendarios, las zonas horarias e incluso los relojes de pulsera inculcan [...] formas de experiencia temporal que parecen naturales...",
    author: "Elisabeth Freeman",
    title: "Time Binds: Queer Temporalities, Queer Histories",
    fullText:
      "<i>La crononormatividad es un modo de implantación, una técnica por la que las fuerzas institucionales llegan a parecer hechos somáticos.</i> <i>Los horarios, los calendarios, las zonas horarias e incluso los relojes de pulsera inculcan</i> lo que el sociólogo Evitar Zerubavel llama 'ritmos ocultos', <i>formas de experiencia temporal que parecen naturales</i> para aquellos a los que benefician. Las manipulaciones del tiempo convierten históricamente regímenes específicos de poder asimétrico en tempos y rutinas corporales aparentemente ordinarios, que, a su vez, organizan el valor y el significado del tiempo.",
  },
  {
    id: 7,
    figure: 2,
    text: "hay un lugar donde el tiempo está detenido. Las gotas de lluvia cuelgan inmóviles en el aire. Los péndulos de los relojes flotan a medio vaivén...",
    author: "Alan Lightman",
    title: "Los sueños de Einstein",
  },
  {
    id: 8,
    figure: 2,
    text: "el tiempo viaja hacia el exterior en círculos concéntricos; en el centro está inmóvil, y se mueve a mayor velocidad a medida que el diámetro aumenta...",
    author: "Alan Lightman",
    title: "Los sueños de Einstein",
    fullText:
      "<i>Hay un lugar donde el tiempo está detenido. Las gotas de lluvia cuelgan inmóviles en el aire. Los péndulos de los relojes flotan a medio vaivén</i>. Los perros alzan sus hocicos en aullidos silenciosos. Los transeúntes están congelados en calles polvorientas, con las piernas alzadas y como sostenidas por hilos. Los aromas de los dátiles, los mangos, el cilantro, el comino permanecen suspendidos en el espacio. <br><br>Cuando un viajero se aproxima a ese lugar desde cualquier dirección, se mueve cada vez más lentamente. Los latidos de su corazón van distanciándose cada vez más, se ralentiza su respiración, desciende su temperatura corporal, se reducen sus pensamientos, hasta que llega al centro exacto y se detiene. Ese es el centro del tiempo. <i>El tiempo viaja hacia el exterior en círculos concéntricos; en el centro está inmóvil, y se mueve a mayor velocidad a medida que el diámetro aumenta<i>. ¿Quién querría hacer una peregrinación hasta el centro del tiempo? Los padres con sus hijos, los amantes.",
  },
  {
    id: 9,
    figure: 2,
    text: "de dónde venimos, a dónde vamos, las preguntas capitales de nuestra existencia vuelven a plantearse en los viajes...",
    author: "Andrea Köhler",
    title: "El tiempo regalado. Un ensayo sobre la espera.",
  },
  {
    id: 10,
    figure: 2,
    text: "viajar es siempre un salto en el tiempo, continuamente vamos en pos de las huellas del primer temor [...]: el peligro de que al volver no nos reconozcan...",
    author: "Andrea Köhler",
    title: "El tiempo regalado. Un ensayo sobre la espera.",
    fullText:
      "<i>Viajar es siempre un salto en el tiempo, continuamente vamos en pos de las huellas del primer temor</i> que acompaña no la marcha, sino también el regreso: <i>el peligro de que al volver no nos reconozcan<i> (del que Ulises es prototipo). Pero toda gran partida tiene una promesa de triunfo: solo por marchar se nos atribuirá nuestro verdadero valor (como al hijo pródigo). Es parte del viaje que alguien espere y dé fe de nuestra ausencia.<br>El ritmo, el rumor y el latido de las olas nos devuelven ese cuerpo que fue el primero que nos hizo transitar el espacio. <i>De dónde venimos, a dónde vamos, las preguntas capitales de nuestra existencia vuelven a plantearse en los viajes.</i> El topos del viaje de la vida no es, por tanto, banal, porque acompaña a la humanidad desde que Ulises se hizo a la mar. Partir, salir de viaje, arribar a otras orillas, constituye, a pesar del desencanto que aguarda al turista, un deseo que no es posible erradicar; procede del Paraíso, y a él nos conducirá.",
  },
  {
    id: 11,
    figure: 2,
    text: "la estandarización de la hora permite a los poderosos controlar el comportamiento de todas las personas que están en la zona horaria estándar...",
    author: "David Rooney",
    title: "A tiempo. Una historia de la civilización en doce relojes.",
    fullText:
      "<i>La estandarización de la hora permite a los poderosos controlar el comportamiento de todas las personas que están en la zona horaria estándar</i>: a qué hora se despiertan, a qué hora se acuestan, cuándo pueden y cuando no pueden comprar alcohol, cuánto tiempo pueden trabajar en las fábricas y en las tiendas, cuánta luz diurna se tiene en verano cuando los días son más largos, con qué facilidad se puede viajar a otros lugares. (...) La próxima vez que nos dirijamos al trabajo en un autobús abarrotado de gente, o que nos veamos metidos en un atasco en hora punta, estaremos obedeciendo a los relojes eléctricos. Más aún, estaremos obedeciendo las órdenes del gobierno, que usa el tiempo para decirnos cómo debemos comportarnos.",
  },
  {
    id: 12,
    figure: 2,
    text: "la antropología surgió y se estableció como un discurso alocrónico; es una ciencia de otros hombres en otro Tiempo...",
    author: "Johannes Fabian",
    title: "Time & the Other. How Anthropology makes its object.",
    fullText:
      "Formulado como una pregunta, el tema de estos ensayos era: ¿cómo la antropología ha estado definiendo o construyendo su objeto, el Otro? La búsqueda de una respuesta se ha guiado por una tesis: <i>la antropología surgió y se estableció como un discurso alocrónico; es una ciencia de otros hombres en otro Tiempo<i>. Es un discurso cuyo referente ha sido alejado del presente del sujeto que habla o que escribe.",
  },
  {
    id: 13,
    figure: 2,
    text: "muchos árboles son potencialmente inmortales, lo que significa que no tienen un programa de senescencia...",
    author: "Francis Hallé",
    title: "La vida de los árboles.",
    fullText:
      "<i>Muchos árboles son potencialmente inmortales, lo que significa que no tienen un programa de senescencia.</i> Si colocamos un árbol en las mejores condiciones posibles durante toda su vida y lo protegemos escrupulosamente de todos los ataques, los peligros y acontecimientos negativos que le puedan ocurrir, nos daremos cuenta de que no muere. Mientras le garanticemos unas condiciones adecuadas, seguirá viviendo y creciendo. ¿Qué es un programa de senescencia? Tomo el caso del ser humano, cuya senescencia es la mejor conocida ya que ha sido la más estudiada. Tenemos 26.000 genes. [...] Conservamos nuestros 26.000 genes hasta nuestro último aliento, aunque la cantidad de genes activos disminuye [por efecto de la metilación: los genes se apagan como si fueran velas]. Unos investigadores españoles de la Universidad de Oviedo han demostrado, recientemente, que esto no ocurre en absoluto de la misma manera con los árboles. Se producen metilaciones, pero durante el año, entre la primavera y el invierno. La primavera siguiente, cuando las yemas se abren, se produce una desmetilación total y el árbol vuelve a tener tantos genes activos como cuando era joven. Estos seres vivos se benefician de la demetilasa, una enzima capaz de retirar el capuchón de la metilación. Algunos gerontólogos se preguntan sobre el por qué de la ausencia de esta enzima en el ser humano.",
  },
  {
    id: 14,
    figure: 2,
    text: "el espacio y el tiempo no solo afectan, sino que también son afectados por todo aquello que sucede en el universo...",
    author: "Stephen W. Hawking",
    title: "Historia del tiempo. Del Big bang a los agujeros negros.",
    fullText:
      "En la teoría de la relatividad general, el espacio y el tiempo son cantidades dinámicas: cuando un cuerpo se mueve, o una fuerza actúa, afecta a la curvatura del espacio y del tiempo y, en contrapartida, la estructura del espacio-tiempo afecta el modo en que los cuerpos se mueven y las fuerzas actúan. <i>El espacio y el tiempo no solo afectan, sino que también son afectados por todo aquello que sucede en el universo.<i>",
  },
  {
    id: 15,
    figure: 2,
    text: "lejos de depender solo de alguna memoria interior y subjetiva, la experiencia cotidiana del tiempo está condicionada por nuestra relación con los objetos y los lugares...",
    author: "Sylviane Agacinski",
    title: "El pasaje: tiempo, modernidad y nostalgia.",
    fullText:
      "<i>Lejos de depender solo de alguna memoria interior y subjetiva, la experiencia cotidiana del tiempo está condicionada por nuestra relación con los objetos y los lugares.<i> <i>Cada persona tiene la edad de sus objetos y experimenta su propio envejecimiento al mismo tiempo que el de sus objetos.</i> La relación con el otro también pasa por las cosas, y nos sentimos contemporáneos de aquellas personas que comparten el mismo mundo material que nosotros. Las distancias entre generaciones consisten sobre todo en los cambios de objetos y de técnicas.",
  },
  {
    id: 16,
    figure: 2,
    text: "la danza del futuro no participa de la estructura narrativa lineal, positiva e insaciable...",
    author: "jaime conde salazar",
    title: "La danza del futuro.",
    fullText: "",
  },
  {
    id: 17,
    figure: 2,
    text: "la danza del futuro existe en muchos tiempos distintos. No es una cosa reciente ni siquiera novedosa. Lleva pasando desde hace mucho tiempo...",
    author: "jaime conde salazar",
    title: "La danza del futuro.",
  },
  {
    id: 18,
    figure: 2,
    text: "la danza del futuro no tiene una forma concreta. O lo que es lo mismo, puede tener cualquier forma...",
    author: "jaime conde salazar",
    title: "La danza del futuro.",
    fullText:
      "La danza del futuro no tiene una forma concreta. O lo que es lo mismo, puede tener cualquier forma. En ese sentido, elude la clasificación clásica según estilos, movimientos, metodologías, géneros o escuelas que resulta a todas luces insuficiente para referirse a la realidad multiforme de la danza del futuro. Quien intente reconocer la danza del futuro buscando una apariencia específica acabará hecho un lío. <br><br><i>La danza del futuro no participa de la estructura narrativa lineal, positiva e insaciable.</i> La danza del futuro no viene después de nada, no viene a mejorar nada, ni a dar de comer a ninguna bestia moderna adicta al consumo de novedad. Porque hace mucho tiempo que sabemos que todo está todo el tiempo. (...) <i>La danza del futuro existe en muchos tiempos distintos. No es una cosa reciente ni siquiera novedosa. Lleva pasando desde hace mucho tiempo.<i> <br><br><i>La danza del futuro no tiene una forma concreta. O lo que es lo mismo, puede tener cualquier forma.</i> En ese sentido, elude la clasificación clásica según estilos, movimientos, metodologías, géneros o escuelas que resulta a todas luces insuficiente para referirse a la realidad multiforme de la danza del futuro. Quien intente reconocer la danza del futuro buscando una apariencia específica acabará hecho un lío.",
  },
  {
    id: 19,
    figure: 2,
    text: "el porvenir es el hecho de que la vida y su fuerza están por todas partes y no pueden pertenecer a ninguno de nosotros, ni como individuo, ni como nación, ni como especie...",
    author: "Emanuele Coccia",
    title: "Metamorfosis. La fascinante continuidad de la vida.",
    fullText:
      "<i>El porvenir es el hecho de que la vida y su fuerza están por todas partes y no pueden pertenecer a ninguno de nosotros, ni como individuo, ni como nación, ni como especie.</i> El porvenir es una enfermedad que obliga a los individuos y a las poblaciones a transformarse. Es una enfermedad que impide que nuestra identidad pueda verse como algo estable, definitivo, real",
  },
  {
    id: 20,
    figure: 2,
    text: "y, de repente, el recuerdo aparece. Es el gusto del trocito de magdalena que (...) mi tía Leonie me daba, después de haberlo mojado en su infusión de té o de tila...",
    author: "Marcel Proust",
    title: "En busca del tiempo perdido.",
    fullText:
      "<i>Y, de repente, el recuerdo aparece. Es el gusto del trocito de magdalena que<i> el domingo por la mañana en Combray (porque ese día yo no salía antes de la hora de misa), cuando iba a darle los buenos días a su habitación, <i>mi tía Leonie me daba, después de haberlo mojado en su infusión de té o de tila<i>. La vista de la pequeña magdalena no me había recordado nada, antes de probarla; quizá porque, habiéndolas visto a menudo después, sin comerlas, sobre las mesas de los pasteleros, su imagen había dejado esos días de Combray para unirse a otros más recientes.",
  },
  {
    id: 21,
    figure: 2,
    text: "(...), uno de los procedimientos a los que recurría el diablo para tentar a los seres humanos, (...) haciéndoles despilfarrar su tiempo, era sin la menor duda los relojes que no estaban en hora...",
    author: "Ahmet Hamdi Tanpinar",
    title: "El Instituto para la sincronización de relojes.",
    fullText:
      "Nuri Efendi quizás fuera más escrupuloso en la sincronización de los relojes que incluso en su reparación. Un reloj que no estuviera en hora bastaba para sacar de sus casillas a aquel hombre tan apacible. Cuando los relojes se multiplicaron en la ciudad, especialmente después de la proclamación de la Constitución, dejó de salir de su sala con el miedo de que vería 'relojes sin estar en hora'. Según él: un reloj que no funcionaba, roto o estropeado, se parecía a una persona enferma. Disculpable por naturaleza. Pero un reloj que no estuviera en hora no tenía ninguna excusa. Era un crimen social, un pecado terrible. En opinión de Nuri Efendi, <i>uno de los procedimientos a los que recurría el diablo para tentar a los seres humanos,<i> para apartarlos del camino recto, <i>haciéndoles despilfarrar su tiempo, era sin la menor duda los relojes que no estaban en hora.<i>",
  },
  {
    id: 22,
    figure: 2,
    text: "en el siglo XIX, rechazar el trabajo es rechazar la normalización del tiempo de la vida en su totalidad, invadida, desde el nacimiento hasta la muerte, por la producción...",
    author: "Maurizio Lazzarato",
    title: "Marcel Duchamp y el rechazo del trabajo.",
    fullText:
      "<i>En el siglo XIX, rechazar el trabajo es rechazar la normalización del tiempo de la vida en su totalidad, invadida, desde el nacimiento hasta la muerte, por la producción.<i> El uso del tiempo que, justamente, constituirá la verdadera obra de arte de Duchamp es el objeto principal del control y de la disciplinarización capitalista. Hay que llevar el tiempo al mercado y transformarlo, intercambiado por el salario, en tiempo de trabajo. El gran rechazo de Duchamp tiene por objeto esa expropiación del tiempo. Ni siquiera el arte tiene el derecho de ocupar y controlar las diferentes temporalidades de la vida",
  },
  {
    id: 23,
    figure: 2,
    text: "ha llegado el momento de cuestionar la euforia de la velocidad y el impulso tecnológico de alcanzarla, haciendo uso de nuestra inventiva para tomar el control de nuestro tiempo durante más tiempo...",
    author: "Judy Wajcman",
    title:
      "Esclavos del tiempo. Vidas aceleradas en la era del capitalismo digital.",
    fullText:
      "Sin embargo, con demasiada frecuencia las reflexiones críticas sobre el impacto de los dispositivos digitales se plantean en términos negativos, como si fuéramos víctimas de una 'crisis' que necesita corrección. Tales lecturas hacen difícil formular una política del tiempo alternativa (y, en particular, una política del tiempo referenciada al género) que no puede separarse del surgimiento de la digitalización, ni de su interrelación con las cambiantes temporalidades de la vida social. Existe una disyunción entre el atractivo cultural de la velocidad y la experiencia común de sentirse siempre apurado, pero esta puede ser una fuente de tensión creativa. Las tecnologías rápidas e inteligentes proporcionan una oportunidad incomparable para alcanzar una sociedad más humana y justa; basta tener presente que el ajetreo no depende de los artilugios en sí, sino de las prioridades y parámetros que nosotros mismos establecemos. <i>Ha llegado el momento de cuestionar la euforia de la velocidad y el impulso tecnológico de alcanzarla, haciendo uso de nuestra inventiva para tomar el control de nuestro tiempo durante más tiempo.<i>",
  },
  {
    id: 24,
    figure: 2,
    text: "el instante, más que ser una unidad de medición del tiempo, es una experiencia temporal particular...",
    author: "Luciano Concheiro",
    title: "Contra el tiempo. Filosofía práctica del instante.",
  },
  {
    id: 25,
    figure: 2,
    text: "nadie puede indicarnos cuál es el camino exacto para experimentar el instante. Cada quien debe encontrar sus propios mecanismos, sus propias prácticas...",
    author: "Luciano Concheiro",
    title: "Contra el tiempo. Filosofía práctica del instante.",
  },

  {
    id: 26,
    figure: 2,
    text: "el instante es una chispa que nos arroja fuera del devenir. Las horas se paralizan, las fechas son abolidas. Sencillamente: el tiempo deja de correr. La sucesión desaparece...",
    author: "Luciano Concheiro",
    title: "Contra el tiempo. Filosofía práctica del instante.",
    fullText:
      "<i>Nadie puede indicarnos cuál es el camino exacto para experimentar el instante. Cada quien debe encontrar sus propios mecanismos, sus propias prácticas.</i> Desde la intimidad, desde la especificidad. Con creatividad e imaginación.<br><br>...<i>el instante, más que ser una unidad de medición del tiempo, es una experiencia temporal particular.</i> Como dice la sabiduría popular, el instante dura apenas unos segundos, pero lo definitorio no es eso, sino que gracias a ese fugaz momento se pierde la noción del pasar del tiempo. <i>El instante es una chispa que nos arroja fuera del devenir. Las horas se paralizan, las fechas son abolidas. Sencillamente: el tiempo deja de correr. La sucesión desaparece.</i>",
  },
  {
    id: 27,
    figure: 2,
    text: "me atraen los tropos temporales vinculados entre sí por una aparente falta de dinamismo o movimiento: esperar, permanecer, retrasarse, aguantar, persistir, repetir, mantenerse, preservar y quedarse...",
    author: "Lisa Baraitser",
    title: "Enduring time.",
    fullText:
      "Mi objetivo es simplemente destacar esos procesos silenciosos, más bien tranquilos, de la estasis psicosocial que parecen producir el cambio a través de la capacidad de alguien para, paradójicamente, permanecer fiel (para usar el término de Badiou) al no-evento, lo que todavía no ha ocurrido, lo que Badiou denominaría situación que todavía no está complementada por el acontecimiento. <i>Me atraen los tropos temporales vinculados entre sí por una aparente falta de dinamismo o movimiento: esperar, permanecer, retrasarse, aguantar, persistir, repetir, mantenerse, preservar y quedarse<i>, en un intento, no tanto de encontrar un respiro a la aceleración de la vida en el capitalismo global digital, sino de investigar el potencial para trascender la inmanencia de nuestro propio momento histórico precisamente en los lugares en los que simplemente parece imposible que ocurra, y de entender esta trascendencia en términos de algo que llamo 'cuidado'.",
  },
  {
    id: 28,
    figure: 2,
    text: "el tiempo no es único: hay una duración distinta para cada trayectoria; transcurre a ritmos diferentes según el lugar y según su velocidad...",
    author: "Carlo Rovelli",
    title: "El orden del tiempo.",
    fullText:
      "<i>El tiempo no es único: hay una duración distinta para cada trayectoria; transcurre a ritmos diferentes según el lugar y según su velocidad.</i> No tiene orientación: la diferencia entre pasado y futuro no existe en las ecuaciones elementales del mundo, es un aspecto contingente que aparece cuando observamos las cosas descuidando los detalles; desde ese enfoque, el pasado del universo se hallaba en un estado curiosamente 'peculiar'. La noción de 'presente' no funciona: en el vasto universo no hay nada que podamos denominar razonablemente como 'presente'.",
  },
  {
    id: 29,
    figure: 3,
    text: "un salón de baile que invita a bailar invocando un tiempo hecho de la suavidad de las palpitaciones de la sangre en las venas...",
    author:
      "Elena Córdoba, Nilo Gallego, Julián Mayorga, Christian Pérez Yates y Laura Ramírez Ashbaugh",
    title: "Salón de baile para bambolear el tiempo",
    image: "SALON1.jpg",
    credits: "Fran M Cabeza de Vaca",
  },
  {
    id: 30,
    figure: 3,
    text: "antes de utilizar los segundos, los tiempos leves se medían con el pulso; lo que tardaba un latido en repetirse era una medida íntima y carnal del tiempo....",
    author:
      "Elena Córdoba, Nilo Gallego, Julián Mayorga, Christian Pérez Yates y Laura Ramírez Ashbaugh",
    title: "Salón de baile para bambolear el tiempo",
    image: "SALON2.jpg",
    credits: "Fran M Cabeza de Vaca",
  },
  {
    id: 31,
    figure: 3,
    text: "invocar un tiempo hecho de la suavidad de los golpes de la sangre, un tiempo que meza nuestros cuerpos, un tiempo muscular y alegre, un tiempo que no nos falte y que nunca nos falle...",
    author:
      "Elena Córdoba, Nilo Gallego, Julián Mayorga, Christian Pérez Yates y Laura Ramírez Ashbaugh",
    title: "Salón de baile para bambolear el tiempo",
    fullText:
      "Esta noche queremos invocar al tiempo para que venga a bailar con nosotras, queremos bambolearlo hasta que olvide el transcurso, la prisa, hasta que no sepa qué va antes y qué va después. Queremos que el tiempo se pierda, que se estanque, que tiemble como lo hacemos nosotras al bailar. Lo queremos incoherente, lo queremos inútil, lo queremos inconsciente, igual que son nuestros bailes. Antes de que existieran los segundos medíamos los tiempos leves con el pulso, lo que tardaba un latido en repetirse era una medida íntima y carnal del tiempo. Esos golpes suaves y graves se metieron en nuestras músicas para sujetar el cuerpo mientras baila, igual que el latido nos sujeta a la vida. <br><br>Esta noche queremos invocar un tiempo hecho de la suavidad de los golpes de la <i> sangre, un tiempo que meza nuestros cuerpos, un tiempo muscular y alegre, un tiempo que no nos falte y que nunca nos falle. Hay tiempo por delante. Hay tiempo por delante. ¿Bailamos???",
  },
  {
    id: 32,
    figure: 3,
    text: "hay tiempo por delante/ hay tiempo por delante/ ¿bailamos?...",
    author:
      "Elena Córdoba, Nilo Gallego, Julián Mayorga, Christian Pérez Yates y Laura Ramírez Ashbaugh",
    title: "Salón de baile para bambolear el tiempo",
  },
  {
    id: 33,
    figure: 3,
    text: "todo tiene su tiempo, y para todo lo que se quiere hay un tiempo bajo el cielo...",
    author:
      "Elena Córdoba, Nilo Gallego, Julián Mayorga, Christian Pérez Yates y Laura Ramírez Ashbaugh",
    title: "Salón de baile para bambolear el tiempo",
  },
  {
    id: 34,
    figure: 3,
    text: "tiempo de endechar, y tiempo de bailar;/ tiempo de esparcir piedras, y tiempo de juntar piedras...",
    author:
      "Elena Córdoba, Nilo Gallego, Julián Mayorga, Christian Pérez Yates y Laura Ramírez Ashbaugh",
    title: "Salón de baile para bambolear el tiempo",
    fullText:
      "Todo tiene su tiempo. Reggaeton del Eclesiates<br><br><i>Todo tiene su tiempo, y para todo lo que se quiere hay un tiempo bajo el cielo.</i><br> Tiempo de nacer, y tiempo de morir;<br> tiempo de plantar, y tiempo de arrancar lo plantado; tiempo de matar, y tiempo de curar;<br> tiempo de destruir, y tiempo de edificar;<br> tiempo de llorar, y tiempo de reír;<br><br>Me gusta la gasolina<br>dame más gasolina.<br><br>tiempo de endechar, y tiempo de bailar;<br>tiempo de esparcir piedras, y tiempo de juntar piedras;<br>tiempo de abrazar, y tiempo de abstenerse de abrazar;<br>tiempo de buscar, y tiempo de perder;<br>tiempo de guardar, y tiempo de desechar;  <br><br>Me gusta la gasolina<br>dame más gasolina<br><br>tiempo de romper, y tiempo de coser;<br>tiempo de callar, y tiempo de hablar;<br> tiempo de amar, y tiempo de aborrecer;<br>tiempo de guerra, y tiempo de paz.<br><br>Me gusta la gasolina<br>dame más gasolina….",
  },
  {
    id: 35,
    figure: 4,
    text: "el Parque del Retiro ofrece la oportunidad de explorar otras temporalidades no regladas...",
    author: "Roberto Martínez",
    title: "Solar 2. El Parque",
    image: "SOLAR1.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores"
  },
  {
    id: 36,
    figure: 4,
    text: "las semillas y las células, las raíces y los pies, las ramas y los brazos, el tronco y la columna vertebral, las hojas y las manos...",
    author: "Roberto Martínez",
    title: "Solar 2. El Parque",
    image: "SOLAR2.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores"
  },
  {
    id: 37,
    figure: 4,
    text: "expansión del centro hacia fuera/ HACIA AFUERA/ EL SOSTENER, EQUILIBRIO/ sujetar/ ZAHORÍ...",
    author: "Roberto Martínez",
    title: "Solar 2. El Parque",
    image: "SOLAR4.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores"
  },
  {
    id: 38,
    figure: 4,
    text: "lo sombrío = donde la vida pasa sin luz/ las piedras/ suelo, debajo del suelo/ gnomos...",
    author: "Roberto Martínez",
    title: "Solar 2. El Parque",
    image: "SOLAR5.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores"
  },
  {
    id: 39,
    figure: 5,
    text: "un acicate queer, travesti y andalusí en una época donde no hay apenas espacio para la escucha, la observación y la experiencia artística...",
    author:
      "Las Niñas (Belial, Berrenga, La Sussi, Agu de Barbate, Rosario Molina, Laca Udilla, Carvento, Pakita)",
    title: "Vida de las niñas",
    image: "NINIAS1.jpeg",
    credits: "Isaac Satnof"
  },
  {
    id: 40,
    figure: 5,
    text: "historia de unas amapolas que escaparon de entre los trigos...",
    author:
      "Las Niñas (Belial, Berrenga, La Sussi, Agu de Barbate, Rosario Molina, Laca Udilla, Carvento, Pakita)",
    title: "Vida de las niñas",
    image: "NINIAS2.jpeg",
    credits: "Isaac Satnof"
  },
  {
    id: 41,
    figure: 5,
    text: "hoy mis amigas, mis amapolas, mis claveles, mis rosas, pensamientos, jazmines y azahares./ Me dan una lección desafiando a la propia historia...",
    author:
      "Las Niñas (Belial, Berrenga, La Sussi, Agu de Barbate, Rosario Molina, Laca Udilla, Carvento, Pakita)",
    title: "Vida de las niñas",
    image: "NINIAS3.jpeg",
    credits: "Isaac Satnof"
  },
  {
    id: 42,
    figure: 5,
    text: "corre, corre, caballito/ trota por la carretera/ no detengas tu carrera...",
    author:
      "Las Niñas (Belial, Berrenga, La Sussi, Agu de Barbate, Rosario Molina, Laca Udilla, Carvento, Pakita)",
    title: "Vida de las niñas",
    image: "NINIAS4.jpeg",
    credits: "Isaac Satnof"
  },
  {
    id: 43,
    figure: 5,
    text: "y lloro sola en mi cama,/ acordándome de mí/ de pensar lo que yo soy/ yo nunca más seré feliz...",
    author:
      "Las Niñas (Belial, Berrenga, La Sussi, Agu de Barbate, Rosario Molina, Laca Udilla, Carvento, Pakita)",
    title: "Vida de las niñas",
    fullText:
      "Poema - Chess <br> Desde el cuarto en cuyas paredes reposa el ábside de una iglesia, se encuentra un maricón<br>dejándose los dedos bordando por la virgen que representa su barrio.<br>Desde el andamio más alto del más alto fresco se encuentra el maricón que embellece de pan<br>de oro nuestro patrimonio.<br>Desde el taller de imaginería que acompaña en su proximidad los yacimientos de arcilla del<br>Guadalquivir, se encuentra el maricon que acaricia con sus manos lo que será la faz de la<br>devoción.<br>Desde los estudios, desde los cuartichines de las casas, desde los camerinos, entre patrones,<br>entre pinturas y materiales nobles. Entre pelo, plumas y joyas.<br>Se encuentran ahí 'Mis niñas de pelo corto'<br>o 'Mis mariquitas que los quiero mucho'<br>Piropos que nacen desde el consuelo, por que decirnos que el arte de España recae sobre<br>nuestros hombros es demasiado para la época.<br>Es demasiado para cualquier época.<br><i>Hoy mis amigas, mis amapolas, mis claveles, mis rosas, pensamientos, jazmines y azahares.</i><br><i>Me dan una lección desafiando a la propia historia.</i><br>Para entrar a defender la contemporaneidad de nuestro arte en un museo siendo travestis.<br>Ya no es necesario morir entre llamas y gritos, ni que te venza la vida después de una paliza, ni<br>dejar el mundo terrenal a consecuencia del sida.<br>Si nos vieran aquellas niñas del pasado, qué contentas estarían de que se nos valorase por lo<br>que aportamos y no por nuestras tragedias.<br><br><br>CORRE, CORRE, CABALLITO (Marisol)<br>Corre, corre, caballito<br>Trota por la carretera<br>No detengas tu carrera <br><br><br>TRAVESTI – PAKITA<br>Nací así, bendecía por la vida<br>y todos hablan de mí.<br>Yo no soy hombre ni mujer,<br>Elegí vivir así<br>Y a mí ya nada me importa<br>Lo que vayas a decir,<br>Porque digas lo que digas<br>Eso no me incumbe a mí.<br>Travestí, travestí, travestí, travestí<br>TRAVESTÍ, TRAVESTÍ, TRAVESTÍ, TRAVESTÍ,<br>En mis noches yo me ensueño,<br>Que se enamoran de mí<br>Qué pesadilla más grande<br>Yo nunca seré feliz<br>De madrugada en tacones<br>Para todos despertar<br>Voy gritando por las calles<br>¡que viva la libertad!<br>Travestí, travestí, travestí, travestí<br>TRAVESTÍ, TRAVESTÍ, TRAVESTÍ, TRAVESTÍ<br><i>Y lloro sola en mi cama,<br>Acordándome de mí<br>De pensar lo que yo soy<br>Yo nunca más seré feliz</i><br>Mi vida es el cabaret<br>Y aquí solo pienso en mí<br>Yo no soy hombre ni mujer<br>Ay yo no tengo que fingir.<br>Travestí, travestí, travestí, travestí<br>TRAVESTÍ, TRAVESTÍ, TRAVESTÍ, TRAVESTÍ<br>TRAVESTÍ, TRAVESTÍ, TRAVESTÍ, TRAVESTÍ",
  },
  {
    id: 44,
    figure: 6,
    text: "invita a pensar en formas alternativas de existir que las comunidades colonizadas construyen más allá de las que les son impuestas...",
    author: "Husos Arquitecturas, Nayare Soledad Otorongx, Karessa M. Ramos",
    title: "Re-existencias Bayanihan",
    image: "BAYANIHAN.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores",
  },
  {
    id: 45,
    figure: 6,
    text: "los tiempos coloniales no conciernen sólo al pasado; siguen vigentes hoy en día...",
    author: "Husos Arquitecturas, Nayare Soledad Otorongx, Karessa M. Ramos",
    title: "Re-existencias Bayanihan",
    image: "BAYANIHAN2.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores",
  },
  {
    id: 46,
    figure: 6,
    text: 'cuestionar un entendimiento de las ideas "tiempo" y "nosotras" en los procesos de diseño...',
    author: "Husos Arquitecturas, Nayare Soledad Otorongx, Karessa M. Ramos",
    title: "Re-existencias Bayanihan",
    image: "BAYANIHAN3.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores",
  },
  {
    id: 47,
    figure: 7,
    text: "un tiempo donde el baile, la política y la vida se expresan en distintas y parecidas proporciones, y ojalá pudieran darse todas ellas a la vez...",
    author: "Fefa Vila",
    title: "Sound Cuts",
    image: "SOUNDCUTS.jpg",
    credits: "Diego Lopez Bueno"
  },
  {
    id: 48,
    figure: 7,
    text: "interrumpir el ritmo,/ el paso,/ la respiración/ Detener el tiempo/ Robar lo que ya se tiene/ Tropezar en la huida...",
    author: "Fefa Vila",
    title: "Sound Cuts",
    image: "SOUNDCUTS2.jpg",
    credits: "Diego Lopez Bueno"
  },
  {
    id: 49,
    figure: 7,
    text: "bailan/ y van por libre...",
    author: "Fefa Vila",
    title: "Sound Cuts",
    image: "SOUNDCUTS3.jpeg",
    credits: "Diego Lopez Bueno",
    fullText:
      "<br>[3-FINAL. 2']<br><br>Romper en mil pedazos<br>Una ventana<br><i>Interrumpir el ritmo,<br>el paso,<br>la respiración<br>Detener el tiempo<br>Robar lo que ya se tiene<br>Tropezar en la huida</i><br>Estallan y corren contra las puertas<br>Era tan frágil...<br>Era tan frágil...<br>Ensordecedor<br>El ruido de lo que se rompe<br>La plusvalía<br>El valor de cambio<br>La nación<br>El estado<br>El sexo<br>El género<br>El Museo<br>Y, ¿La libertad?<br>La libertad<br>Se la toman<br>Se la beben<br>la intercambian<br>La regalan<br>Fracasar torpemente<br>Pero fracasad<br>Alboroto<br>Alegría<br>Baile<br>Bailan<br>y van por libre<br>Una Multitud de Amantes BAILANDO<br>NUNCA Puede Perder",
  },
  {
    id: 50,
    figure: 8,
    text: "nos suspenden en un tiempo elástico, plegado, y exploran otras duraciones posibles del lenguaje desde la poesía y el sonido...",
    author: "Helena Mariño, Enri La Forêt",
    title: "Esta línea es un espacio recíproco de intercambio",
    image: "ESTA_LINEA.jpg",
  },
  {
    id: 51,
    figure: 8,
    text: "los textos que generen presente y presencia, y una densidad afectiva entre el cuerpo propio y el colectivo...",
    author: "Helena Mariño, Enri La Forêt",
    title: "Esta línea es un espacio recíproco de intercambio",
    image: "ESTA_LINEA2.jpg",
  },
  {
    id: 52,
    figure: 8,
    text: "problema número 7/ ¿cómo hablo de mí, cómo hablo de ti, cómo hablo de todas nosotras sin hablar por encima de tu voz?.",
    author: "Helena Mariño, Enri La Forêt",
    title: "Esta línea es un espacio recíproco de intercambio",
    image: "ESTA_LINEA3.jpg",
  },
  {
    id: 53,
    figure: 8,
    text: "así, con tanta prisa, andando a la carretera, no sé de qué vestirme, de qué me quieres ver...",
    author: "Helena Mariño, Enri La Forêt",
    title: "Esta línea es un espacio recíproco de intercambio",
    image: "ESTA_LINEA4.jpg",
  },
  {
    id: 54,
    figure: 8,
    text: "algunos días siento que vivo en un decorado/ una casa blanquísima con puertas de arco, sillas de anea y cuadros con paisajes inverosímiles...",
    author: "Helena Mariño, Enri La Forêt",
    title: "Esta línea es un espacio recíproco de intercambio",
  },
  {
    id: 55,
    figure: 9,
    text: "más atrás:/ está la línea del tiempo/ pero yo no formo parte de ella/ es la línea del tiempo sin mí...",
    author: "Alberto Cortés",
    title: "Los montes son tuyos",
    image: "LOSMONTES_1.jpg",
    credits: "María Mallol",
  },
  {
    id: 56,
    figure: 9,
    text: "¡ôh! Qué bonito este momento, ¿no?...",
    author: "Alberto Cortés",
    title: "Los montes son tuyos",
    image: "LOSMONTES_2.jpg",
    credits: "María Mallol",
  },
  {
    id: 57,
    figure: 9,
    text: "yo hago preguntas por la noche y tengo respuetas por la mañana...",
    author: "Alberto Cortés",
    title: "Los montes son tuyos",
    image: "LOSMONTES_3.jpg",
    credits: "María Mallol",
  },
  {
    id: 58,
    figure: 9,
    text: "el biopoder total que haga colectivo no solo el espacio/ sino sobre todo:/ el tiempo...",
    author: "Alberto Cortés",
    title: "Los montes son tuyos",
  },
  {
    id: 59,
    figure: 10,
    text: "el Sueño como la oportunidad de romper la linealidad temporal de la razón que se piensa como progreso...",
    author: "Elise Florenty, Marcel Türkowsky",
    title: "Tiempo y delirio; sueño y resistencia",
    image: "SUENO1.jpeg",
    credits: "Diego López Bueno",
  },
  {
    id: 60,
    figure: 10,
    text: "delirios que inician la construcción y deconstrucción de una narrativa...",
    author: "Elise Florenty, Marcel Türkowsky",
    title: "Tiempo y delirio; sueño y resistencia",
    image: "SUENO2.jpeg",
    credits: "Diego López Bueno",
  },
  {
    id: 61,
    figure: 10,
    text: "el delirio tiene el poder de alterar el tiempo, las percepciones lineales, las limitaciones de las normas sociales...",
    author: "Elise Florenty, Marcel Türkowsky",
    title: "Tiempo y delirio; sueño y resistencia",
    image: "SUENO3.jpeg",
    credits: "Diego López Bueno",
  },
  {
    id: 62,
    figure: 10,
    text: "¿cómo poder imaginar un pasado o un futuro en un presente que parece no tener fin?...",
    author: "Elise Florenty, Marcel Türkowsky",
    title: "Tiempo y delirio; sueño y resistencia",
  },
  {
    id: 63,
    figure: 10,
    text: "desenterrar las partes de futuro enterradas en el pasado...",
    author: "Elise Florenty, Marcel Türkowsky",
    title: "Tiempo y delirio; sueño y resistencia",
  },
  {
    id: 64,
    figure: 11,
    text: "indagar en torno a la disolución de nuestro tiempo desde la figura conceptual de la ruina...",
    author: "Paz Rojo",
    title: "Ha sido aún no, todavía",
    image: "AUNNO.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores",
  },
  {
    id: 65,
    figure: 11,
    text: "la ruina disuelve el tiempo para nosotrxs, nos permite empezar después del final: escuchar los restos, lo que queda pese a todo...",
    author: "Paz Rojo",
    title: "Ha sido aún no, todavía",
    image: "AUNNO.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores",
  },
  {
    id: 66,
    figure: 11,
    text: "un tiempo que es, a la vez, futural y espectral...",
    author: "Paz Rojo",
    title: "Ha sido aún no, todavía",
    image: "AUNNO2.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores",
  },
  {
    id: 67,
    figure: 11,
    text: "emerger un tercer lugar transitorio, mutante y anacrónico...",
    author: "Paz Rojo",
    title: "Ha sido aún no, todavía",
    image: "AUNNO3.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores",
  },
  {
    id: 68,
    figure: 11,
    text: "la tarea del arte no es la de predecir el futuro, sino la de ser capaz de “ver” el presente o entender la potencialidad futura...",
    author: "Paz Rojo",
    title: "Ha sido aún no, todavía",
    fullText:
      "¿Qué sentidos se abren ante la presencia de un tiempo, un cuerpo y una escena a punto de caerse? A través de la ruina podemos profundizar en el alcance estético de un tiempo que, catastrófica y trágicamente, no nos pertenece. Como figuración temporal y material, <i>la ruina disuelve el tiempo para nosotrxs, nos permite empezar después del final: escuchar los restos, lo que queda pese a todo.</i> A través de la ruina nos dejamos caer, propiciamos el derrumbamiento de las narrativas y los paradigmas que traman nuestra época. Nos abrimos al tiempo de todo aquello que no somos y nos situamos en un escenario poscontemporáneo. En definitiva, experimentamos el encuentro con la estética de un tiempo raro y tremendamente abierto: un tiempo que es, a la vez, futural y espectral. <br><br>Como parte de este planteamiento, proponemos favorecer la comunicación entre los cuerpos que fuimos, los que somos y los que no somos. Desde la dimensión sensible del tacto, transmitimos de un cuerpo a otro lo visible e invisible de las “cosas” (materiales, estructuras, superficies, afectos, sensaciones, imágenes). Además, experimentamos la dimensión material y sonora de cosas casi desaparecidas y olvidadas. Cosas detenidas “cuya poquedad está a la espera”, cosas cuya supervivencia permite dos actitudes vitales: la atención y la escucha. <br><br>Teniendo en cuenta que <i>la tarea del arte no es la de predecir el futuro, sino la de ser capaz de “ver” el presente o entender la potencialidad futura</i>, ¿qué necesitamos para hacerlo posible? Este encuentro es una invitación a pensar en esta pregunta y especular sobre sus implicaciones éticas remontándonos al ámbito de la sensación intuitiva de la estética y, por lo tanto, retomando el sentido griego del theatron cuyo significado alude al “lugar para ver y escuchar en lugar de comunicar”. Para mundificar necesitamos un teatro que permita elaborar formas de “abrir los ojos” a la realidad después de haberlos “cerrado”. Teniendo en cuenta que, lejos de ser un proceso activo y consciente, “ver” es la capacidad de reconocer en nosotrxs el asombro y el misterio que produce la escucha de un campo terriblemente silencioso: el encuentro con un interior que antes no conocíamos.",
  },
  {
    id: 69,
    figure: 12,
    text: "una investigación sobre otras temporalidades posibles...",
    author: "Julieth Morales",
    title: "ISHUWEI MØSIK KØSHPUNINUK (Danza del espíritu femenino)",
    image: "JULIETH_1.jpeg",
    credits: "Kvet Nguyen",
  },
  {
    id: 70,
    figure: 12,
    text: "el lugar para MØSIK KØSHPUNINUK, danza del espíritu femenino...",
    author: "Julieth Morales",
    title: "ISHUWEI MØSIK KØSHPUNINUK (Danza del espíritu femenino)",
    image: "JULIETH_2.jpg",
    credits: "Rafael García Horrillo",
  },
  {
    id: 71,
    figure: 12,
    text: "nos explican que [el cuatro] es nuestro número cosmogónico, el cual mueve a cada intención o gesto al equilibrio y la limpieza...",
    author: "Julieth Morales",
    title: "ISHUWEI MØSIK KØSHPUNINUK (Danza del espíritu femenino)",
    image: "JULIETH_3.jpg",
    credits: "Rafael García Horrillo",
  },
  {
    id: 72,
    figure: 12,
    text: "la revitalización del espíritu, la memoria y el cuerpo en relación con la naturaleza...",
    author: "Julieth Morales",
    title: "ISHUWEI MØSIK KØSHPUNINUK (Danza del espíritu femenino)",
  },
  {
    id: 73,
    figure: 13,
    text: "una empresa a largo plazo, un trabajo riguroso, una obsesión absurda: una aparente pérdida de tiempo...",
    author: "Jéremie Bennequin",
    title: "Learn to rub (time to write)",
    image: "LEARNTORUB_1.jpg",
  },
  {
    id: 74,
    figure: 13,
    text: "tant de liberté et de calme / Ah! voilà quelqu'un / la main / l'altesse / rester une heure / mot...",
    author: "Jéremie Bennequin",
    title: "Learn to rub (time to write)",
    image: "LEARNTORUB_2.jpg",
  },
  {
    id: 75,
    figure: 14,
    text: "“¿qué sueles hacer en esta hora de pausa?”...",
    author: "elii [oficina de arquitectura], Orkan Telhan",
    title: "Restos en suspenso, todavía",
    image: "RESTOS1.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores",

  },
  {
    id: 76,
    figure: 14,
    text: "paisajes ralentizados en los que se suspende su degradación, su mutación, su animación...",
    author: "elii [oficina de arquitectura], Orkan Telhan",
    title: "Restos en suspenso, todavía",
    image: "RESTOS2.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores",
  },
  {
    id: 77,
    figure: 14,
    text: "preservar esta mezcla fluida en una suerte de cápsulas del tiempo a -4ºC...",
    author: "elii [oficina de arquitectura], Orkan Telhan",
    title: "Restos en suspenso, todavía",
    image: "RESTOS3.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores",
  },
  {
    id: 78,
    figure: 14,
    text: '"conversaciones" prolongadas entre los microorganismos y las personas para evidenciar una temporalidad que no pertenece a nadie...',
    author: "elii [oficina de arquitectura], Orkan Telhan",
    title: "Restos en suspenso, todavía",
    image: "RESTOS4.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores",
    fullText:
      "Aquí, los microbios de esos participantes anónimos, mezclados en gruesas capas de tarta de chocolate, se convierten en <i>paisajes ralentizados en los que se suspende su degradación, su mutación, su animación.</i> Pasan a ser unas 'conversaciones' prolongadas entre microorganismos y personas, desplegando una temporalidad distinta que no le pertenece a nadie. Al menos, mientras dure la refrigeración, porque estos otros encuentros en un nuevo tiempo suspendido necesitan ser técnicamente preservados. <br><br>Después, lo que queda se estas conversaciones y restos de comida compartida, que en su momento han formado parte de diferentes contextos, profesiones, clases sociales y distintas micro y macro visiones del mundo, es situado dentro de una red de refrigeradores programada para <i>preservar esta mezcla fluida en una suerte de cápsulas del tiempo a -4ºC.</i>",
  },
  {
    id: 79,
    figure: 15,
    text: "que los sonidos caigan por sí solos... caer, bajar, tocar fondo, derramar, saltar, y fluir...",
    author: "Romina Casile",
    title: "Lo que resuena (escribir un río)",
    image: "ESCRIBIRUNRIO.jpg",
  },
  {
    id: 80,
    figure: 15,
    text: "siempre otra cosa enmedio: siempre umbral, portal, puerta; siempre reino...",
    author: "Romina Casile",
    title: "Lo que resuena (escribir un río)",
    image: "ESCRIBIRUNRIO2.jpg",
  },
  {
    id: 81,
    figure: 15,
    text: "tú y yo estuvimos en el agua antes de conocernos...",
    author: "Romina Casile",
    title: "Lo que resuena (escribir un río)",
    image: "ESCRIBIRUNRIO3.jpg",
  },
  {
    id: 82,
    figure: 15,
    text: "la tarde se convertía en una contradicción...",
    author: "Romina Casile",
    title: "Lo que resuena (escribir un río)",
    image: "ESCRIBIRUNRIO4.jpg",
  },
  {
    id: 83,
    figure: 15,
    text: "el río como metáfora; el río como deriva...",
    author: "Romina Casile",
    title: "Lo que resuena (escribir un río)",
    fullText:
      "<a href='https://www.museoreinasofia.es/multimedia/que-resuena-escribir-rio' target='_blank'>https://www.museoreinasofia.es/multimedia/que-resuena-escribir-rio</a>",
  },
  {
    id: 84,
    figure: 16,
    text: "rellena el tablero alternando colores, como si fuera un tablero de ajedrez...",
    author: "Juan Alonso",
    title: "Píxel Play",
    image: "PIXEL1.jpg",
  },
  {
    id: 85,
    figure: 16,
    text: "on a wall surface, any / continuous stretch of wall, / using a hard pencil, place / fifty points at random...",
    author: "Juan Alonso",
    title: "Píxel Play",
    image: "PIXEL2.jpg",
  },
  {
    id: 86,
    figure: 16,
    text: "elige un color / rellena cuadrados de 2 x 2 notas de ese color, en huecos vacíos o completando otros cuadrados...",
    author: "Juan Alonso",
    title: "Píxel Play",
    image: "PIXEL3.jpg",
  },
  {
    id: 87,
    figure: 17,
    text: "la defensa del deambular como método de reflexión y búsqueda de nuevas perspectivas...",
    author: "Brutalistas (Servando Rocha y David Bizarro)",
    title: "Caminar es magia defensiva",
    image: "CAMINAR1.jpeg",
    credits: "Diego López Bueno"
  },
  {
    id: 88,
    figure: 17,
    text: "pero yo ya había puesto en marcha mi propia magia defensiva, la rutina de resolver los problemas caminando por la ciudad, cazando al vuelo incidentes al azar...",
    author: "Brutalistas (Servando Rocha y David Bizarro)",
    title: "Caminar es magia defensiva",
    image: "CAMINAR2.jpeg",
    credits: "Diego López Bueno"
  },
  {
    id: 89,
    figure: 17,
    text: "el parque del Retiro como umbral a otros tiempos, pasados y futuros...",
    author: "Brutalistas (Servando Rocha y David Bizarro)",
    title: "Caminar es magia defensiva",
    image: "CAMINAR3.jpeg",
    credits: "Diego López Bueno"
  },
  {
    id: 90,
    figure: 18,
    text: "un diálogo en torno a la cadencia no productiva, las temporalidades queer y las posibilidades de enfrentarnos a la celeridad de los ritmos contemporáneos...",
    author: "Azahara Alonso, Adela Franzé, Elena Castro Córdoba",
    title: "Temiendo que se me haga tarde",
    image: "TEMIENDO.jpg",
  },
  {
    id: 100,
    figure: 18,
    text: 'Jacques Derrida nos dice: "el tiempo está fuera de quicio"...',
    author: "Azahara Alonso, Adela Franzé, Elena Castro Córdoba",
    title: "Temiendo que se me haga tarde",
    image: "TEMIENDO2.jpg",
    credits: "Goodbye Dragon Inn, Tsai Ming Liang (2003)"
  },
  {
    id: 101,
    figure: 18,
    text: "en cuanto a paradigmas del tiempo, Pascal Chabot nos habla de destino, progreso, hipertiempo, ocasión y plazo...",
    author: "Azahara Alonso, Adela Franzé, Elena Castro Córdoba",
    title: "Temiendo que se me haga tarde",
  },
  {
    id: 102,
    figure: 18,
    text: "did you know this theater is haunted?...",
    author: "Azahara Alonso, Adela Franzé, Elena Castro Córdoba",
    title: "Temiendo que se me haga tarde",
  },
  {
    id: 103,
    figure: 18,
    text: "el archivo como medio para articular genealogías de la disidencia...",
    author: "Azahara Alonso, Adela Franzé, Elena Castro Córdoba",
    title: "Temiendo que se me haga tarde",
  },
  {
    id: 104,
    figure: 19,
    text: "todos entendemos que el tiempo es un convencionalismo: no es lo mismo que para un agricultor de la Edad Media, que lo medía en las estaciones...",
    author: "Brutalistas (Carlos Arévalo, David Bizarro, Servando Rocha)",
    title: "TIEMPO",
    image: "BRUTALISTAS.jpeg",
  },
  {
    id: 105,
    figure: 19,
    text: 'cuando hablamos de tiempo usamos un lenguaje capitalista: lo invertimos, lo dilapidamos, lo consumimos, "el tiempo es oro"...',
    author: "Brutalistas (Carlos Arévalo, David Bizarro, Servando Rocha)",
    title: "TIEMPO",
  },
  {
    id: 106,
    figure: 19,
    text: "el crononauta se diferencia del viajero en el tiempo en que tiene un propósito: alguien que viaja para cumplir una misión...",
    author: "Brutalistas (Carlos Arévalo, David Bizarro, Servando Rocha)",
    title: "TIEMPO",
  },
  {
    id: 107,
    figure: 1,
    text: "desnaturalizar la experiencia del tiempo lineal, cronométrico, homogéneo, télico, productivo y aceleracionista de nuestra época...",
    author: "Javier Bassas y Raquel Friera",
    title: "Instituto del Tiempo Suspendido",
    fullText:
      "La página del Instituto del Tiempo Suspendido es una página web, claro, y también otras cosas. Quizá es un <i>agujero negro dentro de internet porque atrae y altera el tiempo de quien la visita</i>: si entras y viajas por sus pestañas, sentirás que lo que ven tus ojos, tu relación con el tiempo, la política del mundo y del universo entero no volverán a ser lo que han sido hasta ese momento. También es quizá -no es una alucinación, es real, es personal, es político- un espacio tridimensional: esa página es la “sede virtual” del Instituto del Tiempo Suspendido que refleja las diferentes “sedes físicas” que el ITS ha desplegado en diferentes museos y centros culturales. Y esa página web quizá sería también -como algo alguien que te estaba esperando...- un pecio ante el naufragio temporal de nuestras vidas en pleno neoliberalismo: una barca de salvamento ante el productivismo, un tablón que nos mantendrá a flote para llegar a un lugar (una isla paradisíaca, una ciudad, tu propia casa) donde se suspende el tiempo y se experiencia la cronodiversidad... <br><br>El ITS se orienta, por tanto, <i>hacia la reapropiación del tiempo expropiado, robado, perdido por todas las prácticas que reducen la cronodiversidad constitutiva de los seres</i> (humanos animales vegetales): <i>somos, cada cual, tiempos</i>. <br><br> Como medio de investigación conceptual y de formalizacion estética, el ITS apunta efectivamente a suspender el tiempo, es decir, <i>desnaturalizar la experiencia del tiempo lineal, cronométrico, homogéneo, télico, productivo y aceleracionista de nuestra época.</i> Tal es “la hora occidental”. Se trata, en definitiva, de dar un paso más en el camino de los formatos artísticos, avanzar originalmente en la política de las prácticas estéticas: fundar un instituto, un anti-instituto o un destituto para suspender los ritmos impuestos por la época que nos ha tocado vivir, el neoliberalismo. Es decir, para reapropiarse del tiempo expropiado en el estrés laboral (“La vida no me da”), el falso ocio digital (“Así desconecto”), el extractivismo planetario (“Maquinizar lo vivo y la tierra”), la presión familiar y social que nos impone “no perder tiempo”. <br>Como un instituto (que es también un meta-instituto, un destituto, un antistituto, etc.), el ITS tiene sus “estatutos fundacionales”. Podrían ser diferentes, o quizá no tanto hoy en día, colocados uno después del otro, pero todos de igual importancia: “1. El Instituto del Tiempo Suspendido se funda en un momento preciso de una época precisa, en el llamado neoliberalismo, pero <i>viene de tan lejos en el pasado e incumbe tanto al futuro que su fundación se encuentra, suspendida, dentro y fuera del tiempo</i>.” <br> El ITS entiende el tiempo suspendido de infinitas maneras, pero apuntando siempre y en cualquier caso a maneras de vivir el tiempo que contestan la crononormatividad. La crononormatividad actual está basada en una concepción lineal, homogénea, neutra, cuantitativa, télica, productivista del tiempo: esos ritmos extenuantes y maquinales que se venden como necesarios y naturales.",
    image: "INSTITUTO2.jpeg",
    credits: "Museo Reina Sofía. Fotografía: Joaquín Cortés / Román Lores",
  },
  {
    id: 108,
    figure: 2,
    text: "cada persona tiene la edad de sus objetos y experimenta su propio envejecimiento al mismo tiempo que el de sus objetos...",
    author: "Sylviane Agacinski",
    title: "El pasaje: tiempo, modernidad y nostalgia.",
  },
];
