const content = [
  {
    id: 0,
    figure: 1,
    text: "el delirio de querer vivir muchos ritmos en una sola vida...",
    author: "Javier Bassas y Raquel Friera",
    title: "Instituto del Tiempo Suspendido",
  },
  {
    id: 1,
    figure: 1,
    text: "viene de tan lejos en el pasado e incumbe tanto al futuro que su fundación se encuentra, suspendida, dentro y fuera del tiempo...",
    author: "Javier Bassas y Raquel Friera",
    title: "Instituto del Tiempo Suspendido",
  },
  {
    id: 2,
    figure: 1,
    text: "hacia la reapropiación del tiempo expropiado, robado, perdido por todas las prácticas que reducen la cronodiversidad constitutiva de los seres...",
    author: "Javier Bassas y Raquel Friera",
    title: "Instituto del Tiempo Suspendido",
  },
  {
    id: 3,
    figure: 1,
    text: "un agujero negro dentro de internet porque atrae y altera el tiempo de quien la visita...",
    author: "Javier Bassas y Raquel Friera",
    title: "Instituto del Tiempo Suspendido",
  },
  {
    id: 4,
    figure: 1,
    text: "somos, cada cual, tiempos...",
    author: "Javier Bassas y Raquel Friera",
    title: "Instituto del Tiempo Suspendido",
  },
  {
    id: 5,
    figure: 2,
    text: "la crononormatividad es un modo de implantación, una técnica por la que las fuerzas institucionales llegan a parecer hechos somáticos...",
    author: "Elisabeth Freeman",
    title: "Time Binds: Queer Temporalities, Queer Histories",
  },
  {
    id: 6,
    figure: 2,
    text: "los horarios, los calendarios, las zonas horarias e incluso los relojes de pulsera inculcan [...] formas de experiencia temporal que parecen naturales...",
    author: "Elisabeth Freeman",
    title: "Time Binds: Queer Temporalities, Queer Histories",
  },
  {
    id: 7,
    figure: 2,
    text: "hay un lugar donde el tiempo está detenido. Las gotas de lluvia cuelgan inmóviles en el aire. Los péndulos de los relojes flotan a medio vaivén...",
    author: "Alan Lightman",
    title: "Los sueños de Einstein",
  },
  {
    id: 8,
    figure: 2,
    text: "el tiempo viaja hacia el exterior en círculos concéntricos; en el centro está inmóvil, y se mueve a mayor velocidad a medida que el diámetro aumenta...",
    author: "Alan Lightman",
    title: "Los sueños de Einstein",
  },
  {
    id: 9,
    figure: 2,
    text: "de dónde venimos, a dónde vamos, las preguntas capitales de nuestra existencia vuelven a plantearse en los viajes...",
    author: "Andrea Köhler",
    title: "El tiempo regalado. Un ensayo sobre la espera.",
  },
  {
    id: 10,
    figure: 2,
    text: "viajar es siempre un salto en el tiempo, continuamente vamos en pos de las huellas del primer temor [...]: el peligro de que al volver no nos reconozcan...",
    author: "Andrea Köhler",
    title: "El tiempo regalado. Un ensayo sobre la espera.",
  },
  {
    id: 11,
    figure: 2,
    text: "la estandarización de la hora permite a los poderosos controlar el comportamiento de todas las personas que están en la zona horaria estándar...",
    author: "David Rooney",
    title: "A tiempo. Una historia de la civilización en doce relojes.",
  },
  {
    id: 12,
    figure: 2,
    text: "la antropología surgió y se estableció como un discurso alocrónico; es una ciencia de otros hombres en otro Tiempo...",
    author: "Johannes Fabian",
    title: "Time & the Other. How Anthropology makes its object.",
  },
  {
    id: 13,
    figure: 2,
    text: "muchos árboles son potencialmente inmortales, lo que significa que no tienen un programa de senescencia...",
    author: "Francis Hallé",
    title: "La vida de los árboles.",
  },
  {
    id: 14,
    figure: 2,
    text: "el espacio y el tiempo no solo afectan, sino que también son afectados por todo aquello que sucede en el universo...",
    author: "Stephen W. Hawking",
    title: "Historia del tiempo. Del Big bang a los agujeros negros.",
  },
  {
    id: 15,
    figure: 2,
    text: "lejos de depender solo de alguna memoria interior y subjetiva, la experiencia cotidiana del tiempo está condicionada por nuestra relación con los objetos y los lugares...",
    author: "Sylviane Agacinski",
    title: "El pasaje: tiempo, modernidad y nostalgia.",
  },
  {
    id: 16,
    figure: 2,
    text: "la danza del futuro no participa de la estructura narrativa lineal, positiva e insaciable...",
    author: "jaime conde salazar",
    title: "La danza del futuro.",
  },
  {
    id: 17,
    figure: 2,
    text: "la danza del futuro existe en muchos tiempos distintos. No es una cosa reciente ni siquiera novedosa. Lleva pasando desde hace mucho tiempo...",
    author: "jaime conde salazar",
    title: "La danza del futuro.",
  },
  {
    id: 18,
    figure: 2,
    text: "la danza del futuro no tiene una forma concreta. O lo que es lo mismo, puede tener cualquier forma...",
    author: "jaime conde salazar",
    title: "La danza del futuro.",
  },
  {
    id: 19,
    figure: 2,
    text: "el porvenir es el hecho de que la vida y su fuerza están por todas partes y no pueden pertenecer a ninguno de nosotros, ni como individuo, ni como nación, ni como especie...",
    author: "Emanuele Coccia",
    title: "Metamorfosis. La fascinante continuidad de la vida.",
  },
  {
    id: 20,
    figure: 2,
    text: "y, de repente, el recuerdo aparece. Es el gusto del trocito de magdalena que (...) mi tía Leonie me daba, después de haberlo mojado en su infusión de té o de tila...",
    author: "Marcel Proust",
    title: "En busca del tiempo perdido.",
  },
  {
    id: 21,
    figure: 2,
    text: "(...), uno de los procedimientos a los que recurría el diablo para tentar a los seres humanos, (...) haciéndoles despilfarrar su tiempo, era sin la menor duda los relojes que no estaban en hora...",
    author: "Ahmet Hamdi Tanpinar",
    title: "El Instituto para la sincronización de relojes.",
  },
  {
    id: 22,
    figure: 2,
    text: "en el siglo XIX, rechazar el trabajo es rechazar la normalización del tiempo de la vida en su totalidad, invadida, desde el nacimiento hasta la muerte, por la producción...",
    author: "Maurizio Lazzarato",
    title: "Marcel Duchamp y el rechazo del trabajo.",
  },
  {
    id: 23,
    figure: 2,
    text: "ha llegado el momento de cuestionar la euforia de la velocidad y el impulso tecnológico de alcanzarla, haciendo uso de nuestra inventiva para tomar el control de nuestro tiempo durante más tiempo...",
    author: "Judy Wajcman",
    title:
      "Esclavos del tiempo. Vidas aceleradas en la era del capitalismo digital.",
  },
  {
    id: 24,
    figure: 2,
    text: "el instante, más que ser una unidad de medición del tiempo, es una experiencia temporal particular...",
    author: "Luciano Concheiro",
    title: "Contra el tiempo. Filosofía práctica del instante.",
  },
  {
    id: 25,
    figure: 2,
    text: "nadie puede indicarnos cuál es el camino exacto para experimentar el instante. Cada quien debe encontrar sus propios mecanismos, sus propias prácticas...",
    author: "Luciano Concheiro",
    title: "Contra el tiempo. Filosofía práctica del instante.",
  },

  {
    id: 26,
    figure: 2,
    text: "el instante es una chispa que nos arroja fuera del devenir. Las horas se paralizan, las fechas son abolidas. Sencillamente: el tiempo deja de correr. La sucesión desaparece...",
    author: "Luciano Concheiro",
    title: "Contra el tiempo. Filosofía práctica del instante.",
  },
  {
    id: 27,
    figure: 2,
    text: "me atraen los tropos temporales vinculados entre sí por una aparente falta de dinamismo o movimiento: esperar, permanecer, retrasarse, aguantar, persistir, repetir, mantenerse, preservar y quedarse...",
    author: "Lisa Baraitser",
    title: "Enduring time.",
  },
  {
    id: 28,
    figure: 2,
    text: "el tiempo no es único: hay una duración distinta para cada trayectoria; transcurre a ritmos diferentes según el lugar y según su velocidad...",
    author: "Carlo Rovelli",
    title: "El orden del tiempo.",
  },
  {
    id: 29,
    figure: 3,
    text: "un salón de baile que invita a bailar invocando un tiempo hecho de la suavidad de las palpitaciones de la sangre en las venas...",
    author:
      "Elena Córdoba, Nilo Gallego, Julián Mayorga, Christian Pérez Yates y Laura Ramírez Ashbaugh",
    title: "Salón de baile para bambolear el tiempo",
  },
  {
    id: 30,
    figure: 3,
    text: "antes de utilizar los segundos, los tiempos leves se medían con el pulso; lo que tardaba un latido en repetirse era una medida íntima y carnal del tiempo....",
    author:
      "Elena Córdoba, Nilo Gallego, Julián Mayorga, Christian Pérez Yates y Laura Ramírez Ashbaugh",
    title: "Salón de baile para bambolear el tiempo",
  },
  {
    id: 31,
    figure: 3,
    text: "invocar un tiempo hecho de la suavidad de los golpes de la sangre, un tiempo que meza nuestros cuerpos, un tiempo muscular y alegre, un tiempo que no nos falte y que nunca nos falle...",
    author:
      "Elena Córdoba, Nilo Gallego, Julián Mayorga, Christian Pérez Yates y Laura Ramírez Ashbaugh",
    title: "Salón de baile para bambolear el tiempo",
  },
  {
    id: 32,
    figure: 3,
    text: "hay tiempo por delante/ hay tiempo por delante/ ¿bailamos?...",
    author:
      "Elena Córdoba, Nilo Gallego, Julián Mayorga, Christian Pérez Yates y Laura Ramírez Ashbaugh",
    title: "Salón de baile para bambolear el tiempo",
  },
  {
    id: 33,
    figure: 3,
    text: "todo tiene su tiempo, y para todo lo que se quiere hay un tiempo bajo el cielo...",
    author:
      "Elena Córdoba, Nilo Gallego, Julián Mayorga, Christian Pérez Yates y Laura Ramírez Ashbaugh",
    title: "Salón de baile para bambolear el tiempo",
  },
  {
    id: 34,
    figure: 3,
    text: "tiempo de endechar, y tiempo de bailar;/ tiempo de esparcir piedras, y tiempo de juntar piedras...",
    author:
      "Elena Córdoba, Nilo Gallego, Julián Mayorga, Christian Pérez Yates y Laura Ramírez Ashbaugh",
    title: "Salón de baile para bambolear el tiempo",
  },
  {
    id: 35,
    figure: 4,
    text: "el Parque del Retiro ofrece la oportunidad de explorar otras temporalidades no regladas...",
    author: "Roberto Martínez",
    title: "Solar 2. El Parque",
  },
  {
    id: 36,
    figure: 4,
    text: "las semillas y las células, las raíces y los pies, las ramas y los brazos, el tronco y la columna vertebral, las hojas y las manos...",
    author: "Roberto Martínez",
    title: "Solar 2. El Parque",
  },
  {
    id: 37,
    figure: 4,
    text: "expansión del centro hacia fuera/ HACIA AFUERA/ EL SOSTENER, EQUILIBRIO/ sujetar/ ZAHORÍ...",
    author: "Roberto Martínez",
    title: "Solar 2. El Parque",
  },
  {
    id: 38,
    figure: 4,
    text: "lo sombrío = donde la vida pasa sin luz/ las piedras/ suelo, debajo del suelo/ gnomos...",
    author: "Roberto Martínez",
    title: "Solar 2. El Parque",
  },
  {
    id: 39,
    figure: 5,
    text: "un acicate queer, travesti y andalusí en una época donde no hay apenas espacio para la escucha, la observación y la experiencia artística...",
    author:
      "Las Niñas (Belial, Berrenga, La Sussi, Agu de Barbate, Rosario Molina, Laca Udilla, Carvento, Pakita)",
    title: "Vida de las niñas",
  },
  {
    id: 40,
    figure: 5,
    text: "historia de unas amapolas que escaparon de entre los trigos...",
    author:
      "Las Niñas (Belial, Berrenga, La Sussi, Agu de Barbate, Rosario Molina, Laca Udilla, Carvento, Pakita)",
    title: "Vida de las niñas",
  },
  {
    id: 41,
    figure: 5,
    text: "hoy mis amigas, mis amapolas, mis claveles, mis rosas, pensamientos, jazmines y azahares./ Me dan una lección desafiando a la propia historia...",
    author:
      "Las Niñas (Belial, Berrenga, La Sussi, Agu de Barbate, Rosario Molina, Laca Udilla, Carvento, Pakita)",
    title: "Vida de las niñas",
  },
  {
    id: 42,
    figure: 5,
    text: "corre, corre, caballito/ trota por la carretera/ no detengas tu carrera...",
    author:
      "Las Niñas (Belial, Berrenga, La Sussi, Agu de Barbate, Rosario Molina, Laca Udilla, Carvento, Pakita)",
    title: "Vida de las niñas",
  },
  {
    id: 43,
    figure: 5,
    text: "y lloro sola en mi cama,/ acordándome de mí/ de pensar lo que yo soy/ yo nunca más seré feliz...",
    author:
      "Las Niñas (Belial, Berrenga, La Sussi, Agu de Barbate, Rosario Molina, Laca Udilla, Carvento, Pakita)",
    title: "Vida de las niñas",
  },
  {
    id: 44,
    figure: 6,
    text: "invita a pensar en formas alternativas de existir que las comunidades colonizadas construyen más allá de las que les son impuestas...",
    author: "Husos Arquitecturas, Nayare Soledad Otorongx, Karessa M. Ramos",
    title: "Re-existencias Bayanihan",
  },
  {
    id: 45,
    figure: 6,
    text: "los tiempos coloniales no conciernen sólo al pasado; siguen vigentes hoy en día...",
    author: "Husos Arquitecturas, Nayare Soledad Otorongx, Karessa M. Ramos",
    title: "Re-existencias Bayanihan",
  },
  {
    id: 46,
    figure: 6,
    text: 'cuestionar un entendimiento de las ideas "tiempo" y "nosotras" en los procesos de diseño...',
    author: "Husos Arquitecturas, Nayare Soledad Otorongx, Karessa M. Ramos",
    title: "Re-existencias Bayanihan",
  },
  {
    id: 47,
    figure: 7,
    text: "un tiempo donde el baile, la política y la vida se expresan en distintas y parecidas proporciones, y ojalá pudieran darse todas ellas a la vez...",
    author: "Fefa Vila",
    title: "Sound Cuts",
  },
  {
    id: 48,
    figure: 7,
    text: "interrumpir el ritmo,/ el paso,/ la respiración/ Detener el tiempo/ Robar lo que ya se tiene/ Tropezar en la huida...",
    author: "Fefa Vila",
    title: "Sound Cuts",
  },
  {
    id: 49,
    figure: 7,
    text: "bailan/ y van por libre...",
    author: "Fefa Vila",
    title: "Sound Cuts",
  },
  {
    id: 50,
    figure: 8,
    text: "nos suspenden en un tiempo elástico, plegado, y exploran otras duraciones posibles del lenguaje desde la poesía y el sonido...",
    author: "Helena Mariño, Enri La Forêt",
    title: "Esta línea es un espacio recíproco de intercambio",
  },
  {
    id: 51,
    figure: 8,
    text: "los textos que generen presente y presencia, y una densidad afectiva entre el cuerpo propio y el colectivo...",
    author: "Helena Mariño, Enri La Forêt",
    title: "Esta línea es un espacio recíproco de intercambio",
  },
  {
    id: 52,
    figure: 8,
    text: "problema número 7/ ¿cómo hablo de mí, cómo hablo de ti, cómo hablo de todas nosotras sin hablar por encima de tu voz?.",
    author: "Helena Mariño, Enri La Forêt",
    title: "Esta línea es un espacio recíproco de intercambio",
  },
  {
    id: 53,
    figure: 8,
    text: "así, con tanta prisa, andando a la carretera, no sé de qué vestirme, de qué me quieres ver...",
    author: "Helena Mariño, Enri La Forêt",
    title: "Esta línea es un espacio recíproco de intercambio",
  },
  {
    id: 54,
    figure: 8,
    text: "algunos días siento que vivo en un decorado/ una casa blanquísima con puertas de arco, sillas de anea y cuadros con paisajes inverosímiles...",
    author: "Helena Mariño, Enri La Forêt",
    title: "Esta línea es un espacio recíproco de intercambio",
  },
  {
    id: 55,
    figure: 9,
    text: "más atrás:/ está la línea del tiempo/ pero yo no formo parte de ella/ es la línea del tiempo sin mí...",
    author: "Alberto Cortés",
    title: "Los montes son tuyos",
  },
  {
    id: 56,
    figure: 9,
    text: "¡ôh! Qué bonito este momento, ¿no?...",
    author: "Alberto Cortés",
    title: "Los montes son tuyos",
  },
  {
    id: 57,
    figure: 9,
    text: "yo hago preguntas por la noche y tengo respuetas por la mañana...",
    author: "Alberto Cortés",
    title: "Los montes son tuyos",
  },
  {
    id: 58,
    figure: 9,
    text: "baja ángel Gabriel/ baja aquí/ ahora/ delante de este público/ y anúncianos algo...",
    author: "Alberto Cortés",
    title: "Los montes son tuyos",
  },
  {
    id: 59,
    figure: 10,
    text: "el Sueño como la oportunidad de romper la linealidad temporal de la razón que se piensa como progreso...",
    author: "Elise Florenty, Marcel Türkowsky",
    title: "Tiempo y delirio; sueño y resistencia",
  },
  {
    id: 60,
    figure: 10,
    text: "delirios que inician la construcción y deconstrucción de una narrativa...",
    author: "Elise Florenty, Marcel Türkowsky",
    title: "Tiempo y delirio; sueño y resistencia",
  },
  {
    id: 61,
    figure: 10,
    text: "el delirio tiene el poder de alterar el tiempo, las percepciones lineales, las limitaciones de las normas sociales...",
    author: "Elise Florenty, Marcel Türkowsky",
    title: "Tiempo y delirio; sueño y resistencia",
  },
  {
    id: 62,
    figure: 10,
    text: "¿cómo poder imaginar un pasado o un futuro en un presente que parece no tener fin?...",
    author: "Elise Florenty, Marcel Türkowsky",
    title: "Tiempo y delirio; sueño y resistencia",
  },
  {
    id: 63,
    figure: 10,
    text: "desenterrar las partes de futuro enterradas en el pasado...",
    author: "Elise Florenty, Marcel Türkowsky",
    title: "Tiempo y delirio; sueño y resistencia",
  },
  {
    id: 64,
    figure: 11,
    text: "indagar en torno a la disolución de nuestro tiempo desde la figura conceptual de la ruina...",
    author: "Paz Rojo",
    title: "Ha sido aún no, todavía",
  },
  {
    id: 65,
    figure: 11,
    text: "la ruina disuelve el tiempo para nosotrxs, nos permite empezar después del final: escuchar los restos, lo que queda pese a todo...",
    author: "Paz Rojo",
    title: "Ha sido aún no, todavía",
  },
  {
    id: 66,
    figure: 11,
    text: "un tiempo que es, a la vez, futural y espectral...",
    author: "Paz Rojo",
    title: "Ha sido aún no, todavía",
  },
  {
    id: 67,
    figure: 11,
    text: "emerger un tercer lugar transitorio, mutante y anacrónico...",
    author: "Paz Rojo",
    title: "Ha sido aún no, todavía",
  },
  {
    id: 68,
    figure: 11,
    text: "la tarea del arte no es la de predecir el futuro, sino la de ser capaz de “ver” el presente o entender la potencialidad futura...",
    author: "Paz Rojo",
    title: "Ha sido aún no, todavía",
  },
  {
    id: 69,
    figure: 12,
    text: "una investigación sobre otras temporalidades posibles...",
    author: "Julieth Morales",
    title: "ISHUWEI MØSIK KØSHPUNINUK (Danza del espíritu femenino)",
  },
  {
    id: 70,
    figure: 12,
    text: "el lugar para MØSIK KØSHPUNINUK, danza del espíritu femenino...",
    author: "Julieth Morales",
    title: "ISHUWEI MØSIK KØSHPUNINUK (Danza del espíritu femenino)",
  },
  {
    id: 71,
    figure: 12,
    text: "nos explican que [el cuatro] es nuestro número cosmogónico, el cual mueve a cada intención o gesto al equilibrio y la limpieza...",
    author: "Julieth Morales",
    title: "ISHUWEI MØSIK KØSHPUNINUK (Danza del espíritu femenino)",
  },
  {
    id: 72,
    figure: 12,
    text: "la revitalización del espíritu, la memoria y el cuerpo en relación con la naturaleza...",
    author: "Julieth Morales",
    title: "ISHUWEI MØSIK KØSHPUNINUK (Danza del espíritu femenino)",
  },
  {
    id: 73,
    figure: 13,
    text: "una empresa a largo plazo, un trabajo riguroso, una obsesión absurda: una aparente pérdida de tiempo...",
    author: "Jéremie Bennequin",
    title: "Learn to rub (time to write)",
  },
  {
    id: 74,
    figure: 13,
    text: "tant de liberté et de calme / Ah! voilà quelqu'un / la main / l'altesse / rester une heure / mot...",
    author: "Jéremie Bennequin",
    title: "Learn to rub (time to write)",
  },
  {
    id: 75,
    figure: 14,
    text: "“¿qué sueles hacer en esta hora de pausa?”...",
    author: "elii [oficina de arquitectura], Orkan Telhan",
    title: "Restos en suspenso, todavía",
  },
  {
    id: 76,
    figure: 14,
    text: "paisajes ralentizados en los que se suspende su degradación, su mutación, su animación...",
    author: "elii [oficina de arquitectura], Orkan Telhan",
    title: "Restos en suspenso, todavía",
  },
  {
    id: 77,
    figure: 14,
    text: "preservar esta mezcla fluida en una suerte de cápsulas del tiempo a -4ºC...",
    author: "elii [oficina de arquitectura], Orkan Telhan",
    title: "Restos en suspenso, todavía",
  },
  {
    id: 78,
    figure: 14,
    text: '"conversaciones" prolongadas entre los microorganismos y las personas para evidenciar una temporalidad que no pertenece a nadie...',
    author: "elii [oficina de arquitectura], Orkan Telhan",
    title: "Restos en suspenso, todavía",
  },
  {
    id: 79,
    figure: 15,
    text: "que los sonidos caigan por sí solos... caer, bajar, tocar fondo, derramar, saltar, y fluir...",
    author: "Romina Casile",
    title: "Lo que resuena (escribir un río)",
  },
  {
    id: 80,
    figure: 15,
    text: "siempre otra cosa enmedio: siempre umbral, portal, puerta; siempre reino...",
    author: "Romina Casile",
    title: "Lo que resuena (escribir un río)",
  },
  {
    id: 81,
    figure: 15,
    text: "tú y yo estuvimos en el agua antes de conocernos...",
    author: "Romina Casile",
    title: "Lo que resuena (escribir un río)",
  },
  {
    id: 82,
    figure: 15,
    text: "la tarde se convertía en una contradicción...",
    author: "Romina Casile",
    title: "Lo que resuena (escribir un río)",
  },
  {
    id: 83,
    figure: 15,
    text: "el río como metáfora; el río como deriva...",
    author: "Romina Casile",
    title: "Lo que resuena (escribir un río)",
  },
  {
    id: 84,
    figure: 16,
    text: "rellena el tablero alternando colores, como si fuera un tablero de ajedrez...",
    author: "Juan Alonso",
    title: "Píxel Play",
  },
  {
    id: 85,
    figure: 16,
    text: "on a wall surface, any / continuous stretch of wall, / using a hard pencil, place / fifty points at random...",
    author: "Juan Alonso",
    title: "Píxel Play",
  },
  {
    id: 86,
    figure: 16,
    text: "elige un color / rellena cuadrados de 2 x 2 notas de ese color, en huecos vacíos o completando otros cuadrados...",
    author: "Juan Alonso",
    title: "Píxel Play",
  },
  {
    id: 87,
    figure: 17,
    text: "la defensa del deambular como método de reflexión y búsqueda de nuevas perspectivas...",
    author: "Brutalistas (Servando Rocha y David Bizarro)",
    title: "Caminar es magia defensiva",
  },
  {
    id: 88,
    figure: 17,
    text: "pero yo ya había puesto en marcha mi propia magia defensiva, la rutina de resolver los problemas caminando por la ciudad, cazando al vuelo incidentes al azar...",
    author: "Brutalistas (Servando Rocha y David Bizarro)",
    title: "Caminar es magia defensiva",
  },
  {
    id: 89,
    figure: 17,
    text: "el parque del Retiro como umbral a otros tiempos, pasados y futuros...",
    author: "Brutalistas (Servando Rocha y David Bizarro)",
    title: "Caminar es magia defensiva",
  },
  {
    id: 90,
    figure: 18,
    text: "un diálogo en torno a la cadencia no productiva, las temporalidades queer y las posibilidades de enfrentarnos a la celeridad de los ritmos contemporáneos...",
    author: "Azahara Alonso, Adela Franzé, Elena Castro Córdoba",
    title: "Temiendo que se me haga tarde",
  },
  {
    id: 100,
    figure: 18,
    text: 'Jacques Derrida nos dice: "el tiempo está fuera de quicio"...',
    author: "Azahara Alonso, Adela Franzé, Elena Castro Córdoba",
    title: "Temiendo que se me haga tarde",
  },
  {
    id: 101,
    figure: 18,
    text: "en cuanto a paradigmas del tiempo, Pascal Chabot nos habla de destino, progreso, hipertiempo, ocasión y plazo...",
    author: "Azahara Alonso, Adela Franzé, Elena Castro Córdoba",
    title: "Temiendo que se me haga tarde",
  },
  {
    id: 102,
    figure: 18,
    text: "did you know this theater is haunted?...",
    author: "Azahara Alonso, Adela Franzé, Elena Castro Córdoba",
    title: "Temiendo que se me haga tarde",
  },
  {
    id: 103,
    figure: 18,
    text: "el archivo como medio para articular genealogías de la disidencia...",
    author: "Azahara Alonso, Adela Franzé, Elena Castro Córdoba",
    title: "Temiendo que se me haga tarde",
  },
  {
    id: 104,
    figure: 19,
    text: "todos entendemos que el tiempo es un convencionalismo: no es lo mismo que para un agricultor de la Edad Media, que lo medía en las estaciones...",
    author: "Brutalistas (Carlos Arévalo, David Bizarro, Servando Rocha)",
    title: "TIEMPO",
  },
  {
    id: 105,
    figure: 19,
    text: 'cuando hablamos de tiempo usamos un lenguaje capitalista: lo invertimos, lo dilapidamos, lo consumimos, "el tiempo es oro"...',
    author: "Brutalistas (Carlos Arévalo, David Bizarro, Servando Rocha)",
    title: "TIEMPO",
  },
  {
    id: 106,
    figure: 19,
    text: "el crononauta se diferencia del viajero en el tiempo en que tiene un propósito: alguien que viaja para cumplir una misión...",
    author: "Brutalistas (Carlos Arévalo, David Bizarro, Servando Rocha)",
    title: "TIEMPO",
  },
  {
    id: 107,
    figure: 9,
    text: "el biopoder total que haga colectivo no solo el espacio/ sino sobre todo:/ el tiempo...",
    author: "Alberto Cortés",
    title: "Los montes son tuyos",
  },
];
